language: php

notifications:
  email:
    on_success: never
    on_failure: change

branches:
  only:
    - master

php:
  - 5.6

env:
  - WP_VERSION=latest WP_MULTISITE=0

before_script:
  - composer self-update
  - composer install --prefer-source
  - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION

script: phpunit
